name: Build and Release Windows EXE

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller gui_app.spec

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui_app-exe
          path: dist/gui_app.exe
        if: always()

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gui_app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 